### ISSUE TITLE
RFC: How might we price licensing Compensated for commercial use?

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/compensated#22]
At the moment, we have [one commercial user](https://www.notabli.com) who has a license granted due to existing revenue share agreements with the collective. However, there's another client that is evaluating the use of compensated for their own purposes.

The thoughts in my head are:

1. Is there a a minimum annual cost? 
2. What about a percentage of gross revenue?
3. How can we ensure that cost isn't a significant factor in adoption decisions while still making sure it's enough to keep the project sustainable?
4. Do we offer discounts for multi-year licenses?

For reference, some pricing tables for proprietary, privately sourced subscription management platforms:

- MoonClerk: https://www.moonclerk.com/pricing/
- Recurly: https://recurly.com/plans/
- Gumroad: https://gumroad.com/features/pricing

**Comment by maximegalon5** [comment]
I think a combination of a basic annual subscription (monthly or discounted annual upfront), along with a certain percentage (competitive) of the transaction (tiered tranches) is a good model. I have figures in mind, which I'll share offline.

**Comment by zspencer** [comment]
Here's how I'm thinking of modeling it:

$50/yr minimum licensing fee for commercial use by an individual or organization that is earning less than $75,000/yr in revenue (Median annual household income in the U.S.)

Licensees earning $75,000/yr+ in gross receipts have a base cost of $500/yr plus $0.001c for every dollar in gross receipts in a given month. This way as the organization scales, we have a piece of the upside but it's not so high as to be cost prohibitive.

**Comment by zspencer** [comment]
Also, it seems there are probably three different commercial licenses we may want to price for:

1. Single entity commercial use, where the licensee may use Compensated in their programs that collect money on behalf of only themselves.
2. Multi-entity commercial use, where the licensee may use Compensated in their programs that collect money on behalf of themselves _and_ other legal entities.
3. Reseller Licensing, where the licensee may use Compensated in programs owned by other entities. (For instance, if an agency wants to bundle it into client projects without requiring the client to have to figure out the licensing rights)

Further, this is pricing distinct from a hosted offering which we may choose to provide at some point if we want to compete more directly with Moonclerk/Recurly/etc.

**Comment by drllau** [comment]
OK Zee, what you are describing is 

1.  DIY subscription service which is a step-function y = f(t,x) = { 0 : t< 1,  $500: x<75k, $5000+0.1%x: x>75k) 
2. D4U [done for you] = hosted = $one-off setup fee + ???% of receipts (pure payment processor who is governed by ??? state law and is compliant (read exempted)  from the Money Service Business (MSB) regulations and report to the U.S. Department of the Treasury’s Financial Crimes Enforcement Network (FinCEN). There may be a threshold where volume requires mandatory reporting
3. a custom bespoke version P.O.A but basically time and materials (eg bandwdth) but they probably keep 100% of receipts since likely to be internal use

Problems

- your step function is discontinuous .. don't know if it will be gamed, 75k is roughly $200/day so jumping 500->5000 s like 3 weeks work. 
- multiple entities ... I assume that your aggregation of $5000 allows for a set of Internet Payment Interfaces 
- reseller bundling ... its a Function as a Service, you just provide the container, add in a credit for the one month trial ($400) as per LicenseZero and start the ticker running from first use

**Comment by zspencer** [comment]
Hey @drllau! Thank you!

I think what we have landed on for now is that we provide licenses for particular major versions (0.X, 1.X) and that if we do wind up offering this as a hosted service; charge a tiny percentage of gross proceeds.

This gets around the step function problem; as well as encourages our customers to contribute back to the version they have the license for; as they are not going to be charged again to continue using Compensated.

From a bundling perspective; my instinct is that if we license Compensated to someone for use in their project, and that project does nothing with compensated beyond "redistribute" the compensated package; then we would want whoever uses compensated the bundled distribution to pay a license fee if they use it for commercial use.

However, if they bundle Compensated into another project that provides an alternative value proposition (i.e. an online store as a service) then I would like us to figure out a way to have a small percentage of the revenue they generate that are enabled by Compensated.

This is a non-trivial challenge to solve from a "how do we even write that contract up?" This makes me think that it will be simplest to continue with the strategy of alpha customers pay a one-time fee and can do whatever they want with it; and as we determine a better set of terms of use for future sales we can add more clear restrictions or pricing models.

**Comment by drllau** [comment]
> provide licenses for particular major versions

OK, so that means automatic upgrade within major iterations ... now DEFINE the product map for each for me.

That was the problem (from a purely legal PoV) when I looked at the License Zero ... whilst intentful a decent lawyer (not even international) would poke enough holes to create uncertainty. So you want me to alter text in CONTRIBUTION for $500 one-off for single/non-profit and $5000 for anyone else (along with waivers for special cases). But I'm unclear WHAT title you are selling so I can't write the appropriate legal guff (and the Zero License is not helping as not many are familar ... I can see why it was rejected by the OSI despite author claiming it fufills the intent).

> project does nothing with compensated beyond "redistribute" the compensated package; then we would want whoever uses compensated the bundled distribution to pay a license fee if they use it for commercial use.

The way around this is to have a master server license which supports say 1000x client licenses. So you can either add some value and onsell the $500 (keeping the client licenses) or individually use it for say $50 each client (so long as you get a unique MAC or IPv6 address). I think I can implement this using some multi-party signature but what budget do you have for testing? There's also the escalating clause seen in art world where each time a sculpture is resold, the original artists gets a %.

**Comment by zspencer** [comment]
Thank you! This is super useful! 

Re: Budget - I do not have any budget at present because we're locking down to weather the COVID-19 pandemic. 

Re: Roadmap - For now, I think the boring baseline of "You get unlimited rights to use 0.X and 1.X for $500. If you don't feel comfortable buying until we have a more clear roadmap for what goes into 0.X and 1.X that is 100% OK." The @zinc-collective/compensated-maintainers will do our best to earn that trust over the coming months." Our goal is to follow [SemVer](https://semver.org/) and make as few breaking changes as possible once we hit 1.X.

Re: Additional licensing - While at present, we do not have a clear enough value proposition for a more complex licensing model; I think your points regarding escalating clauses and a per-user metered plan makes a lot of sense. 

Thank you again! This is both helpful and useful!

**Comment by maximegalon5** [comment]
Update: The business model is slated for discussion during ZC's upcoming meeting.

**Comment by zspencer** [comment]
We have decided to do organizational pricing on a case-by-case, as each enterprise will have different financial needs.
