### ISSUE TITLE
Dead links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ghost** [zinc-collective/compensated#44]
`CONTRIBUTING.md` is really well written so far, but there are a couple dead links leading to [`design/README.md` and `design/ARCHITECTURE.md`](https://github.com/zinc-collective/compensated/blob/0.X/CONTRIBUTING.md#learn-the-system).

**Comment by drllau** [comment]
+1 @lanegrant (welcome to Zinc Coop), appreciate the reminder as Zee and I were having some access issues trying to merge including trying to upload some files. @zspencer if you can assign this to me I'll fix up the linkrot before it gets worse. We really also need to get a [sandbox](https://codesandbox.io) working so can test out some working examples (just payment + reversecharge until no money, then reset).

**Comment by zspencer** [comment]
Thank you @lanegrant  - I intend to sprout a `docs/` folder today and place the contents I was planning to put in `design/README.md` and `design/ARCHITECTURE.md` in there so that our documentation lives both in-repo and on the web..

@drllau - great point re: sandbox. Made a ticket - https://github.com/zinc-collective/compensated/issues/45 

I'm not entirely sure I'm comfortable handing off the design and architecture documentation just yet; because there's a lot of things that I've learned over the last two years that I need to put into them; but I'll 100% tag you to review the patch I'm going to make today with the documentation!

**Comment by drllau** [comment]
@zspencer , my laptop power supply just carked it so I'll be offline maybe weekend (or longer) to transfer my HD so get back to this next week.

**Comment by zspencer** [comment]
No worries! Stay safe!

**Comment by zspencer** [comment]
@lanegrant - can you verify that these broken links are still a problem for you? Apologies for the delay I'm spinning about 5 plates too many ATM :); and strugglign to accept that my role isn't as much about driving feature work forward and is more about making it easier for people to contribute.

**Comment by ghost** [comment]
The broken links are fixed. Thank you
